### ISSUE TITLE
7 de Diciembre no es festivo

### ISSUE THREAD

**Issue by xantiagoma** [Angelfire/es-festivo#2]
<img width="1170" alt="Screen Shot 2021-12-01 at 11 02 46 AM" src="https://user-images.githubusercontent.com/1217807/144269221-495c462b-f311-4233-a396-c12329ac58fd.png">

Hola,
Genial el proyecto,
Una cosa no se si es un error de datos pero el festivo es el 8 de Diciembre no el 7.

**Comment by Angelfire** [comment]
Que tal @xantiagoma, no, no es un error de los datos, parece ser un error con el tiempo del servidor, localmente las fechas están como corresponde :/

Gracias por reportar!

**Comment by Angelfire** [comment]
@xantiagoma El problema ha sido corregido!
